### ISSUE TITLE
Library duplication

### ISSUE THREAD

**Issue by d3xt3r2909** [imsujan276/easy_linkedin_login#1]
Hi, I'm the owner of the [LinkedIn login plugin](https://pub.dev/packages/linkedin_login). As I can see this is a duplication of my library which is also a public source. So it would be a smart idea to submit PRs and not duplicate and take over my code ;] All the best

**Comment by imsujan276** [comment]
Tried creating a [PR](https://github.com/d3xt3r2909/linkedin_login/pull/65).  I have updated the package as per my need and added few customizations but as per your response, it would be a breaking changes for existing users. I have given the credit to the origin plugin though :)
