### ISSUE TITLE
[BUG] Unable to fetch access token code AuthCodeException

### ISSUE THREAD

**Issue by nayanAubie** [imsujan276/easy_linkedin_login#2]
- When running your example project with your credentials, it's working.
- but when running your example project with my credentials, it gives me `AuthCodeException`
- The entire message is `Unable to fetch access token code AuthCodeException:: for authCode: Scope r_liteprofile is not authorized for your application with description: unauthorized_scope_error`

**Flutter version:** 3.13.4
**easy_linkedin_login:** ^1.0.3

### My code snippet

```dart
LinkedInButtonStandardWidget(
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => LinkedInUserWidget(
                    redirectUrl: kLinkedInRedirectUrl,
                    clientId: kLinkedInClientId,
                    clientSecret: kLinkedInClientSecret,
                    onGetUserProfile: (linkedInUser) async {
                      print('Access token ${linkedInUser.user.token.accessToken!}');
                      print('First name: ${linkedInUser.user.firstName!.localized!.label!}');
                      print('Last name: ${linkedInUser.user.lastName!.localized!.label!}');
                      Navigator.pop(context);
                    },
                    onError: (e) {
                      print('Error: ${e.toString()}');
                      Navigator.pop(context);
                    },
                  ),
                ),
              );
            },
          )
```

### Logs
flutter: : LinkedInAuth-steps: navigationDelegate ...
flutter: : LinkedInAuth-steps: navigationDelegate [currentUrL: https://www.linkedin.com/developers/tools/oauth/redirect?error=unauthorized_scope_error&error_description=Scope+%26quot%3Br_liteprofile%26quot%3B+is+not+authorized+for+your+application&state=cbcc2773-73b6-4d58-9dda-9fe89f2fe421, isCurrentMatch: true]
flutter: : LinkedInAuth-steps: Fetching access token...
flutter: : LinkedInAuth-steps:fetchAccessTokenCode: parsing authorization code...
flutter: : Navigation delegate prevent... done
flutter: LinkedInLogin: Unable to fetch access token code AuthCodeException:: for authCode: Scope+%26quot%3Br_liteprofile%26quot%3B+is+not+authorized+for+your+application with description: unauthorized_scope_error
flutter: Error: UserFailedAction{exception: AuthCodeException:: for authCode: Scope+%26quot%3Br_liteprofile%26quot%3B+is+not+authorized+for+your+application with description: unauthorized_scope_error}

#### The app is verified on the developer site and `Sign In with LinkedIn using OpenID Connect` & `Share on LinkedIn` are available under added products
<img width="350" alt="Screenshot 2023-09-14 at 12 04 19 PM" src="https://github.com/imsujan276/easy_linkedin_login/assets/109264909/61fab281-1aa4-4cd6-bed8-65278ebb23ae">
<img width="350" alt="Screenshot 2023-09-14 at 12 04 34 PM" src="https://github.com/imsujan276/easy_linkedin_login/assets/109264909/6cac262a-c1db-4025-b035-e8a160bd732b">

**Comment by imsujan276** [comment]
You need to add the product "**Sign In with LinkedIn**" instead of "**Sign In with LinkedIn using OpenID Connect**"

[Product preview](https://ibb.co/LzLWsqM)

**Comment by nayanaubie** [comment]
FYI @imsujan276 , "Sign In with LinkedIn" is removed and in place of it, "Sign In with LinkedIn using OpenID Connect" is added

**Comment by imsujan276** [comment]
@nayanAubie  I did not know that. Looks like I will have to look into it in detail. Thak you for bringing this up

**Comment by imsujan276** [comment]
I have looked into the update LinkedIn has made. They have removed the product **Sign In with LinkedIn** completely. So, it may need a major update in the plugin to adapt to the changes. I have little time because of my projects so I may not be actively working on this issue. 

### Any Pull Requests regrading this is Welcome.

**Comment by nayanaubie** [comment]
I can make it but unfortunately, I made an entirely new package in my organization for quick setup.
https://pub.dev/packages/signin_with_linkedin

Thank you for your reply.

**Comment by imsujan276** [comment]
That's great.
